# Generated by Django 3.2.25 on 2024-04-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriterecipe',
            options={'default_related_name': '%(class)ss', 'ordering': ('-recipe__pub_date',), 'verbose_name': 'Избранные рецепты', 'verbose_name_plural': 'Избранные рецепты'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'default_related_name': '%(class)ss', 'ordering': ('ingredient__name',)},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'default_related_name': '%(class)ss', 'ordering': ('recipe',)},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'default_related_name': '%(class)ss', 'ordering': ('-recipe__pub_date',), 'verbose_name': 'Корзина покупок', 'verbose_name_plural': 'Корзина покупок'},
        ),
    ]
